### ISSUE TITLE
Its not possible to upload any file after update to RC5

### ISSUE THREAD

**Issue by DTX-92** [madoublet/respond#455] opened 2016-08-29 22:29 UTC
There is no Plus button in files section.
![image](https://cloud.githubusercontent.com/assets/20479161/18069644/3311d7b4-6e51-11e6-999e-8660bc2ff43c.png)

**Comment by madoublet** [comment] 2016-08-29 22:54
Thanks!  Not sure what is going on.  I am guessing it was related to the component changes in RC5.  It looks like the file uploader is missing from galleries as well.  I will investigate and issue a fix soon.

**Comment by madoublet** [comment] 2016-08-31 02:21
Should be fixed now.

**Comment by axis80** [comment] 2016-11-22 08:03
Confirmed fixed in RC2 branch.

**Closed by axis80** 2016-11-22 08:03 UTC
