### ISSUE TITLE
SiteMap 

### ISSUE THREAD

**Issue by markvgo** [madoublet/respond#295] opened 2015-05-18 05:27 UTC
Rather than manually building a footer menu it would be good to have a site map.

A method like PublishSite->PublishMenuJSON() could build a menu (site map) with each pagetype as a menu item with a submenu. 

Each submenu (PageType) would have a menuItem for each page for that PageType.

**Comment by madoublet** [comment] 2015-05-18 13:00
Respond does build the sitemap.xml file automatically.  If you want a visual sitemap, it is really easy to build using the list component (see http://respondcms.com/plugin/list).  Just drag a list for each page type onto the screen.

**Comment by markvgo** [comment] 2015-05-19 22:04
Thanks 
Good to know about the list component and the sitemap.xml but I was  meaning something like the footer of this site www.seek.com. 

What I really meant was a footer menu with all the site. But not a high priority, I will build footer up manually.

**Comment by madoublet** [comment] 2015-05-21 02:52
You can probably use the same concept in the footer (e.g. repond-list).  I am going to close this b/c it is not a bug.

**Closed by madoublet** 2015-05-21 02:52 UTC
