### ISSUE TITLE
can this CMS be hoseted on Github Pages?

### ISSUE THREAD

**Issue by fullstackpiyush** [madoublet/respond#530] opened 2017-07-22 09:44 UTC
I wanna host my CMS on github pages.
I have recently deployed an Angular App on github pages
As you know it only supports static sites .
will respond cms support github pages

**Comment by madoublet** [comment] 2017-07-25 18:33
You can publish sites generated with Respond to Github pages, but the CMS itself will not currently run on Github pages.  In the future, it will be possible to run the front-end of the application via the respond-ui project (https://github.com/madoublet/respond-ui) but this is still a WIP.

**Comment by madoublet** [comment] 2017-07-25 18:34
Closing b/c this is not a bug.

**Closed by madoublet** 2017-07-25 18:34 UTC

**Comment by vchrizz** [comment] 2019-03-11 11:48
I've got the same question, not as bug, but as feature-request.
Guess the OP was misunderstood.
Not the respond app itself should be hosted on Github Pages, because that is impossible due to Github allowing only static content.
Instead the **generated content** by respond app should be hosted on Github.
In respond settings, there are options to sync to Amazon S3, so some sync to GithubPages would be appreciated.
(at the moment i do this 'manually' by script i have to run after clicking publish in respond)

**Comment by madoublet** [comment] 2019-03-11 12:12
@vchrizz I recently changed direction and removed the AWS Sync from Respond.  It is not b/c I think it is a bad feature but because it was painful to maintain.  I personally think that hosting your website on AWS or Github makes a lot of sense.  But, at the same time, it is so easy to automate this using a daily CRON job in combination with the AWS CLI or Github CLI, that this is probably the best way to do this going forward.

**Comment by vchrizz** [comment] 2019-03-11 12:24
@madoublet good point, but from user's point of view its rather complicated i guess. so i would put up some short how-to or step-by-step tutorial on how to accomplish that.
even for my part, as technician, it was not that easy i think, first i had to setup a key to be able to deploy without logging in every time the script runs, then i had to work out the script to push the generated content to github.
my choice on respond was that it seems is the only static-content-generator with integrated editor and really easy management of the whole site. i barely had to touch any code. thats what impressed me about respond. now having to deal with so much "behing-the-scenes"-stuff makes it less user-friendly i guess?
